# Generated by Django 2.2.2 on 2019-07-06 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='location',
        ),
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(default='example@email.com', max_length=70),
        ),
        migrations.AddField(
            model_name='profile',
            name='first_name',
            field=models.CharField(default='your firstname', max_length=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_name',
            field=models.CharField(default='your lastname', max_length=30),
        ),
    ]
